### PR TITLE
Update Apptimize to 2.12.3

### PR DESCRIPTION
**Pull request by honeybeep**

### CODE REVIEW

**Comment by samdozor** [comment]
Hey @honeybeep - thanks for the PR! Would you mind flattening these commits into a single commit, and then rebasing the latest master from our repo onto your master branch? Right now the histories are totally diverged.

**Comment by honeybeep** [comment]
@samdozor how's this?

**Comment by samdozor** [comment]
Much better!

Question for you - are you seeing your SDK be initialized off the main thread? We essentially have the same check prior to calling onKitCreate: https://github.com/mParticle/mparticle-android-sdk/blob/master/android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java#L78

**Comment by honeybeep** [comment]
@slenkjon

**Comment by jsaptmz** [comment]
@honeybeep if the mParticle SDK itself guarantees it then we probably don't need to have it in our code as well.

**Comment by samdozor** [comment]
Indeed - we will always guarantee this as it's pretty much a universal requirements of our integration partners.

**Comment by honeybeep** [comment]
all righty then this has become a very small pull

**Pull request merged**
